### PR TITLE
Update Ghidra to 11.0

### PR DESCRIPTION
**Pull request by evan-a-a**
Includes flathubbot commit and dependency update

Superseeds #69

### CODE REVIEW

**Comment by evan-a-a** [comment]
bot, build

**Comment by evan-a-a** [comment]
@hadess, would appreciate a look :slightly_smiling_face:

**Comment by hadess** [comment]
> This is not compatible with Ghidra 11.0 and can be added via the
> plugin system if required

There's no plugin as explained in https://github.com/NationalSecurityAgency/ghidra/pull/4103

Please remove that part of the sentence.

What did you use to generate the updated dependencies?

**Comment by evan-a-a** [comment]
> There's no plugin as explained in [NationalSecurityAgency/ghidra#4103](https://github.com/NationalSecurityAgency/ghidra/pull/4103)

According to the upstream repo (https://github.com/nneonneo/ghidra-wasm-plugin#prebuilt-extension) this can be installed via plugin/extension system, if it were compatible with 11.0. I don't think carrying an out of tree patch in the flatpak makes much sense. 

> What did you use to generate the updated dependencies?

The dependencies script from the repo.

**Comment by hadess** [comment]
> According to the upstream repo (https://github.com/nneonneo/ghidra-wasm-plugin#prebuilt-extension) this can be installed via plugin/extension system, if it were compatible with 11.0. I don't think carrying an out of tree patch in the flatpak makes much sense anyway.

I was under the impression that the upstream repo was outdated and wouldn't be updated as the pull request mentioned. But there's this issue: https://github.com/nneonneo/ghidra-wasm-plugin/pull/17

> The dependencies script from the repo.

Good to know somebody else managed to use it successfully ;)

**Pull request merged**
