### PR TITLE
Use stable branch to generate deps

### PR DESCRIPTION
**Pull request by mpi3d**
I forgot to use the stable branch to generate deps

### CODE REVIEW

**Comment by hadess** [comment]
> I forgot to use the stable branch to generate deps

Do we need to also update the generated dependencies file?

**Comment by mpi3d** [comment]
> > I forgot to use the stable branch to generate deps
> 
> Do we need to also update the generated dependencies file?

No, generated dependencies are the same for this version. When I run `generate-deps.sh` it generates the same file. (Except that the order differ)

**Comment by hadess** [comment]
> No, generated dependencies are the same for this version. When I run `generate-deps.sh` it generates the same file. (Except that the order differ)

Great, thanks.

**Comment by mpi3d** [comment]
No problem

**Pull request merged**
